# Generated by Django 2.2.6 on 2021-06-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210604_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='add_domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Add_domain',
        ),
    ]
