# Generated by Django 2.2.6 on 2021-06-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20210604_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
